num_epoch: 1000
num_episodes: 10
num_episodes_baseline: 50
# num_episodes_baseline: 5
# lr: 0.01
lr: 0.0005
clip_value: 0.1
entropy_reg_strength: 0.2
# entropy_reg_strength: 0.05
risk_epsilon: 0.5

instance_path: "./examples/len1024taxa50"

reload_checkpoint_path: "./checkpoints/20260519-160820taxa50_lenmixed2320_gtr+i+g_randomlambda_Highway_FuseAttnXRest_real_NoNorm_hgWoMeanWoMLP_EncAttnl6_h8_sharedAGG_BalancedELU_dim64_lr0.0005_woclip_decay0.98_margin0.5_patch1_bs1_RawTopo_BtmTopTraj_MSATransEnc_dropout0.4/checkpoint_final_epoch_10_step270000.pt"


env:
  # batch_size: 4
  batch_size: 1
  # batch_size: 128
  # BATCH_SIZE: 8
  sequence_type: DNA_WITH_GAP

model:
  vocab_size: 4
  patch_size: 1
  # fixed_length: 1024
  embed_dim: 64
  num_enc_heads: 8
  num_enc_layers: 6